a=input("enter name of student1:")
b=input("enter his marks",) 
c=input("enter name of student2:")
d=input("enter his marks",) 
e=input("enter name of student3:")
f=input("enter his marks",) 
print(a, b) 
print(c, d) 
print(e, f) 