a=str(input("enter name of student1:"))
b=int(input("enter his marks",)) 
c=str(input("enter name of student2:"))
d=int(input("enter his marks",)) 
e=str(input("enter name of student3:"))
f=int(input("enter his marks",)) 
print(a, b) 
print(c, d) 
print(e, f) 
